name: Destroy Azure environment

on:
  push:
    branches:
      - "destroy-env"

env:
  AZURE_RESOURCE_GROUP: cd-with-actions
  #################################################
  ### USER PROVIDED VALUES ARE REQUIRED BELOW   ###
  #################################################
  #################################################
  ### REPLACE WITH THE ID OF YOUR SUBCRIPTION   ###
  AZURE_SUBSCRIPTION_ID: 123-abc-4d5e
  #################################################

jobs:
  Setup-Azure-Resources:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Destroy Azure environment
        if: success()
        run: |
          az group delete --name ${{env.AZURE_RESOURCE_GROUP}} --subscription fa14ea09-0454-4d1c-985d-f83432419acc --yes
