name: Azure Production deployment

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: npm install and build webpack
        run: |
          npm install
          npm run build
      - uses: actions/upload-artifact@master
        with:
          name: webpack artifacts
          path: public/

  Build-Docker-Image:
    runs-on: ubuntu-latest
    needs: build
    name: Build image and store in GitHub Packages
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Download built artifact
        uses: actions/download-artifact@master
        with:
          name: webpack artifacts
          path: public

      - name: Build, Tag, Push
        uses: mattdavis0351/actions/docker-gpr@update-docker-action
        id: dockerImage
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          image-name: bread-crumbs

      - name: "Login via Azure CLI"
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy web app container
        uses: azure/webapps-container-deploy@v1
        with:
          app-name: "actions-ttt"
          images: ${{ steps.dockerImage.outputs.imageUrl }}

      - name: Azure logout
        run: |
          az logout
  # Deploy-to-Azure:
  #   runs-on: ubuntu-latest
  #   needs: Build-Docker-Image
  #   name: Deploy app container to Azure
  #   steps:
  #     - name: Download built artifact
  #       uses: actions/download-artifact@master
  #       with:
  #         name: webpack artifacts
  #         path: public
  #     - name: "Login via Azure CLI"
  #       uses: azure/login@v1
  #       with:
  #         creds: ${{ secrets.AZURE_CREDENTIALS }}
  #     - name: Deploy web app container
  #       uses: azure/webapps-container-deploy@v1
  #       with:
  #         app-name: "actions-ttt"
  #         images: ${{ steps.dockerImage.outputs.imageUrl }}
  #     - name: Azure logout
  #       run: |
  #         az logout
